title: "Building Websites in Github"

description: "This research project develops training materials for researchers who want to learn to build project website in github with GitHub Pages."

email: "teamcarp@tudelft.nl"
twitter: "https://twitter.com/thecarpentries"
team_members: [
    {name: "Tom Cat", role: "project lead", start_date: "2020-02-01"},
    {name: "Jane Smith", role: "maintainer", start_date: "2018-03-15"},
    {name: "Albert Hamilton", role: "editor", start_date: "2017-12-01"},
    {name: "Alice Dauncey", role: "developer", start_date: "2020-09-15"},
]
collections: 
    - posts:
        output: true
